version: "3.8"

services:
  postgres:
    image: postgres:16-alpine3.19
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
